### ISSUE TITLE
How to get link for Watch now in Netflix or amazon Prime?

### ISSUE THREAD

**Issue by SimonPeter1909** [RatakondalaArun/tmdb_api#10]
I think the image below will explain the issue...

how to get the link for Netflix and other streaming services?

![image](https://user-images.githubusercontent.com/24413796/78896275-d920bc00-7a8d-11ea-8564-30b07c9f7f6f.png)

**Comment by Arunnaidu3470** [comment]
> I think the image below will explain the issue...
> 
> how to get the link for Netflix and other streaming services?
> 
> ![image](https://user-images.githubusercontent.com/24413796/78896275-d920bc00-7a8d-11ea-8564-30b07c9f7f6f.png)

### Sorry, but the current version of TMDB API doesn't provide any Streaming partner info. It may be available in feature versions.
