### ISSUE TITLE
Can you add include_image_language option to movie/tv getDetails?

### ISSUE THREAD

**Issue by 0Franky** [RatakondalaArun/tmdb_api#101]
Hi @biner88 ,
first of all thank you for your contribution!

As the title suggests, I'd like to have option include_image_language in tmdb.v3.movies.getDetails and tmdb.v3.tv.getDetails method.

Can you help me?

Thanks in advance and have a nice day!

**Comment by RatakondalaArun** [comment]
closed in #102
