### ISSUE TITLE
Append to response in movies.getDetails doesn't work.

### ISSUE THREAD

**Issue by Viswanth1038** [RatakondalaArun/tmdb_api#16]
**it calls appendToResponse instead of append_to_response**

![image](https://user-images.githubusercontent.com/30171132/85542344-9efb9b00-b636-11ea-96dc-d86f51664682.png)
false is the value of map.containsKey('credits')

**Comment by RatakondalaArun** [comment]
Fixed with pull request #17 by @Viswanth1038 

Thanks for your contribution dude.
