### ISSUE TITLE
feature: migration to Null safety

### ISSUE THREAD

**Issue by RatakondalaArun** [RatakondalaArun/tmdb_api#18]
https://medium.com/dartlang/announcing-sound-null-safety-defd2216a6f3

- Null safety is backwards compatible

**components to migrate**

- [x] Core
- [x] v3
- [x] v4

**Comment by biscottis** [comment]
Hi, any updates on the null-safety migration?

**Comment by RatakondalaArun** [comment]
Hello👋, Waiting for this package to support null safety https://github.com/iamsalnikov/colorize/pull/8
