### ISSUE TITLE
Exception while making a request. Exception = {SocketException: OS Error: Connection reset by peer, errno = 104, address = api.themoviedb.org, port = 54384

### ISSUE THREAD

**Issue by ParthPahuja101** [RatakondalaArun/tmdb_api#26]
hey,
I'm using get to fetch the movie list but sometime it works and sometime it shows this error => "Exception while making a request. Exception = {SocketException: OS Error: Connection reset by peer, errno = 104, address = api.themoviedb.org, port = 54384"

**Comment by RatakondalaArun** [comment]
Check the device internet connection

If it is possible can you share reproducible code?
