### ISSUE TITLE
Error when use auth.createSessionWithLogin

### ISSUE THREAD

**Issue by ThomasCarrillo** [RatakondalaArun/tmdb_api#34]
Hi !

When i want to use v3.auth.createSessionWithLogin i have this error : 

**E/flutter (25249): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, String>'
E/flutter (25249): #0      Auth.createSessionWithLogin (package:tmdb_api/versions/v3/category/authentication.dart:206:44)
E/flutter (25249): <asynchronous suspension>
E/flutter (25249): #1      TMDBApi.loginWithCredentials (package:tmdb_authentication/tmdb_api.dart:17:9)
E/flutter (25249): <asynchronous suspension>
E/flutter (25249): #2      _LoginScreenState.build.<anonymous closure> (package:tmdb_authentication/screens/Login.dart:77:21)
E/flutter (25249): <asynchronous suspension>
E/flutter (25249):**

Here my code :

```
import 'package:tmdb_api/tmdb_api.dart';

class TMDBApi {
  final String apiKey = "myApiKey";
  final String apiReadAccessV4 =
      "myAccesV4";
  TMDB tmdb;

  var requestToken;

  TMDBApi() {
    tmdb = new TMDB(ApiKeys(apiKey, apiReadAccessV4));
  }

  loginWithCredentials() async {
    await tmdb.v3.auth.createSessionWithLogin("myUsername", "myPassword");
  }
}
```

I call loginWithCredentials on button click.

Do you have any idea please ?

**Comment by RatakondalaArun** [comment]
Let me check
