### ISSUE TITLE
Could you add cache?  it would be great

### ISSUE THREAD

**Issue by willsalasare** [RatakondalaArun/tmdb_api#57]
![Screenshot_20210816-225002.png](https://user-images.githubusercontent.com/35855979/129661158-c7edc4b1-0547-439c-af9d-b027b1a368a7.png)

**Comment by RatakondalaArun** [comment]
Hello @willsalasare, This is a good idea. But it requires migrate from `http` to `dio`. Is it worth that?

**Comment by RatakondalaArun** [comment]
@willsalasare added caching support with a1c6963. It will get published in next release

**Comment by RatakondalaArun** [comment]
- closed in (#71)
