### ISSUE TITLE
Update CI workflows

### ISSUE THREAD

**Issue by RatakondalaArun** [RatakondalaArun/tmdb_api#60]
Update [ci.yaml](https://github.com/RatakondalaArun/tmdb_api/blob/development/.github/workflows/ci.yml) workflows to only run on `pull_request` from `development` and `master` branches

**Comment by pp2659** [comment]
I will work on it

**Comment by RatakondalaArun** [comment]
Sure

**Comment by Gopal-Dahale** [comment]
@RatakondalaArun I have already created a pr for this; requires your approval for running workflows.

**Comment by RatakondalaArun** [comment]
@Gopal-Dahale sorry looked @pp2659 reply before looking at PR

**Comment by Gopal-Dahale** [comment]
Not a problem. Thanks.

**Comment by RatakondalaArun** [comment]
closed by #61
@Gopal-Dahale Thanks for your contribution 🎉.
